### PR TITLE
198 wrong preview for multi record queries

### LINKED ISSUE #198: Wrong preview for multi-record queries
Record preview is wrong for multi-record query results.

**Repro**
1. Open https://play.reduct.store
2. Query panel → bucket `datasets` → entries `*`
3. Run:
```json
{"$limit":100}
```
4. Check record 16 preview

**Expected**
Record 16 is a cat image.

**Actual**
Record 16 preview shows a number.

Image

### PR DESCRIPTION
**Pull request by AnthonyCvn**
Closes #198

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix

### What was changed?

(Describe the changes)

### Related issues

https://github.com/reductstore/reductstore/pull/1326

### Does this PR introduce a breaking change?

No

### CODE REVIEW

File: src/Components/RecordPreview/RecordPreview.tsx [hunk 1]
```diff
@@ -87,12 +87,15 @@ const RecordPreview: React.FC<RecordPreviewProps> = ({
...
+        recordEntryName ??
+        (typeof entryName === "string" ? entryName : entryName[0]);
       const generatedQueryLink = await bucket.createQueryLink(
         entryName,
-        queryStart ?? timestamp,
+        queryStart,
         queryEnd,
         queryOptions,
-        recordIndex ?? 0,
+        { entry: resolvedEntryName, timestamp },
```
Comment (atimin) [inline src/Components/RecordPreview/RecordPreview.tsx:98]: fanny, it's working without update of the sdk =D.

File: package.json [hunk 2]
```diff
@@ -28,12 +28,11 @@
     "react": "^19.0.0",
     "react-dom": "^19.0.0",
     "react-router-dom": "^7.0.0",
-    "reduct-js": "^1.19.1",
+    "reduct-js": "^1.19.2",
```
Comment (atimin) [inline package.json]: it works with v1.19.2, but it's more reliable to bump it up to 1.19.3

**Review by atimin — CHANGES_REQUESTED** [review]

File: src/Components/RecordPreview/RecordPreview.tsx (hunk 1 above)
Comment (AnthonyCvn) [reply src/Components/RecordPreview/RecordPreview.tsx:98]: really? i didn't try with `1.19.2`

**Review by atimin — APPROVED** [review]
